export enum Severity {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL",
}

export enum IncidentType {
  MALICIOUS_JWT = "MALICIOUS_JWT",
  BRUTE_FORCE = "BRUTE_FORCE",
  SCANNER_DETECTED = "SCANNER_DETECTED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  SUSPICIOUS_PAYLOAD = "SUSPICIOUS_PAYLOAD",
  SECURITY_TOGGLE = "SECURITY_TOGGLE",
}
