export enum ConversationStatus {
  OPEN = "OPEN",
  BOT_ACTIVE = "BOT_ACTIVE",
  HUMAN_INTERVENTION = "HUMAN_INTERVENTION",
  BLOCKED = "BLOCKED",
  WAITING_AGENT = "WAITING_AGENT",
  HANDOFF = "HANDOFF",
  CLOSED = "CLOSED",
  ARCHIVED = "ARCHIVED",
}
