services:

  postgres:

    image: postgres:16

    container_name: abiel-postgres

    restart: always

    environment:

      POSTGRES_USER: abiel

      POSTGRES_PASSWORD: abiel

      POSTGRES_DB: abiel


    ports:

      - "5432:5432"


    volumes:

      - postgres_data:/var/lib/postgresql/data


volumes:

  postgres_data: